language: python
python:
- '3.7'
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm install 13.7.0
- nvm use 13.7.0
- rm -rf node_modules
- npm install
- sudo -H pip install --upgrade setuptools
- sudo -H pip install --upgrade pip wheel requests pyopenssl
- sudo -H pip install --ignore-installed six
- sudo -H pip install --upgrade tox twine
- pip install --upgrade setuptools
- pip install --upgrade web3 aiohttp requests cryptography pyopenssl
- pip2 install requests[security]
- git pull --tags
- sudo apt-get install php-pear
- sudo apt-get install php-dev
- sudo apt-get install libcurl4-openssl-dev
- sudo pecl install ds
- php -r 'phpinfo();'
- composer install
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  npm config set git-tag-version=false && NPM_VERSION=$(npm version patch); fi
- cp package.json LICENSE.txt keys.json python
- npm run build
- cd python
- tox -e doc
- cd ..
- travis_terminate 0
- npm run test-base
- set +e
- node run-tests --js --python 5; export TESTS_FAILED=$?
- set -e
- if [ "$TESTS_FAILED" -ne 0 ]; then exit 1; fi
after_failure:
- dmesg | grep -i kill
- sleep 4
notifications:
  slack:
    secure: ktACBU+k1AL0SXKHKNcEkWjx5Tha7OWyO1YeirwDxnQiI1KPfgs0sx8FenzBuH9imob3fU4DSpftIC9Zpa9pRIyKApIOMw3aGG4tY8DYiV7zTaHxs4GKHug2BdUG+U2/h6iaulS7CxiqVf9/6aZFMhYT+Dl3tbof0+Xin9OKXLc2QGSgjzHoxBu1FrHEMIqcoKzKHP7PHWTY7xSDvBHwuf4waAmXxuAw91xOCzYCteTcNS0vlHsP+fBlw7thySsn0T4ZDIjLYnlDacUbYeUXjJ2akzOSfd1+v53gVW5C9+3LoXwdUw35kGG/NSetdvxXt36dtdYRNRoX33hwxIoizP7MoIhQ2x7i9Q6hnT7N05Eu4xuYfIQrTcoD+2LWYtOYRjRJuJnHf9cI/vwSXii+P+ESXpTACjszREA/JvpL/WTUOXkbdgsubVLahCkLF6fab1zs/kNzQY//aw4P60v50hcNawenbMkhKyz5KXCsePyc+6rCgVJWYaontfjPudj4xmdpD9F87steboS6HVkYC/ED+D6XyC+MyDi3MjJ/RJ7OV0f+eZO7UoLFWvQPuv3bkUa8VhQjjiyrdNVOEIgUGhJ/OT//88aIWW2Qr4IaQulqAyUFQJd4NhbJuQbIr4vnJu0MEAVND6zM1fdRyS3LnncmPya/XhnnEQBkqLBfaFg=
