language: python
python:
- '3.7'
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm install 13.7.0
- nvm use 13.7.0
- rm -rf node_modules
- npm install
- sudo -H pip install --upgrade setuptools
- sudo -H pip install --upgrade pip wheel requests pyopenssl
- sudo -H pip install --ignore-installed six
- sudo -H pip install --upgrade tox twine
- pip install --upgrade setuptools
- pip install --upgrade web3 aiohttp requests cryptography pyopenssl
- pip install ccxt
- pip2 install requests[security]
- git pull --tags
- pecl install ds
- php -i | grep php.ini
- sudo ls -alh /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20170718/
- sudo tail /home/travis/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- composer install
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  npm config set git-tag-version=false && NPM_VERSION=$(npm version patch); fi
- cp package.json LICENSE.txt keys.json python
- npm run build
# - npm run test-base
- set +e
- node run-tests --js --python --php; export TESTS_FAILED=$?
- set -e
- if [ "$TESTS_FAILED" -ne 0 ]; then exit 1; fi
- echo ${GITHUB_TOKEN}
# - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then env COMMIT_MESSAGE=${NPM_VERSION:1} GITHUB_TOKEN=${GITHUB_TOKEN} ./build/push.sh; fi
after_failure:
- dmesg | grep -i kill
- sleep 4
notifications:
  slack:
    secure: ktACBU+k1AL0SXKHKNcEkWjx5Tha7OWyO1YeirwDxnQiI1KPfgs0sx8FenzBuH9imob3fU4DSpftIC9Zpa9pRIyKApIOMw3aGG4tY8DYiV7zTaHxs4GKHug2BdUG+U2/h6iaulS7CxiqVf9/6aZFMhYT+Dl3tbof0+Xin9OKXLc2QGSgjzHoxBu1FrHEMIqcoKzKHP7PHWTY7xSDvBHwuf4waAmXxuAw91xOCzYCteTcNS0vlHsP+fBlw7thySsn0T4ZDIjLYnlDacUbYeUXjJ2akzOSfd1+v53gVW5C9+3LoXwdUw35kGG/NSetdvxXt36dtdYRNRoX33hwxIoizP7MoIhQ2x7i9Q6hnT7N05Eu4xuYfIQrTcoD+2LWYtOYRjRJuJnHf9cI/vwSXii+P+ESXpTACjszREA/JvpL/WTUOXkbdgsubVLahCkLF6fab1zs/kNzQY//aw4P60v50hcNawenbMkhKyz5KXCsePyc+6rCgVJWYaontfjPudj4xmdpD9F87steboS6HVkYC/ED+D6XyC+MyDi3MjJ/RJ7OV0f+eZO7UoLFWvQPuv3bkUa8VhQjjiyrdNVOEIgUGhJ/OT//88aIWW2Qr4IaQulqAyUFQJd4NhbJuQbIr4vnJu0MEAVND6zM1fdRyS3LnncmPya/XhnnEQBkqLBfaFg=
env:
  global:
    secure: CQBKPcipKTvfgBi8KXaJ6KyjJL5GcWPEW7WrKZcTeM2AaNqTX8w3yuqjsezxVnQWLG3TzEI0m1K31Fv9wfZHsMwRIr5py6AeAc4C2JgaKs3FSAFJ3m46a9hK7FIeC0xMdXszPJx7534XiuG8nMJRbwbNNswb35GekysKU87g5Sf6U7UFFeyyyQdchiPF85lYBt/AJSArNsfHMd0RKQY5pHdAHNNB70qFECIBeC6MYiUFBHydw2ist/bSWa9GYEh3LxUNMQ7bbxuzD6+sVMU2PW61gEpa3I9HB7NTQvPp+YbYWqBwS++SKCuqkalXdMPeCIINu64T1UtFGZNWvw9xfg8T8GwGHwZnNZ1o3WCXKo9/+FC70OAb76mblEXllhQs+gBL5g/bqdQBKfGrYIACHBRE3pzNPSRn7oY3hpk7NLoJRbB28OQ5ymJrDc8hctoXwgD3KrIM91+6YqycOifidLFHecg/VA2bjSx/ql69sVhNchaBJ8b7EMMIjo1DrFIv43XJ7DHX+2yZFJD8uv5eCGHkfXv6XfV5312TYzGYsxpfJ9my9tdTGxop2BXzaf1nYqrI+RPKIZrh6FgiXgRaetwRpWl4G+DqxKbKtfzYlZtYU2JeJ7Z5AMwLHyvxxcuOH3MrE+vk5nbU5gE9E3m5o7yH+d7Qj5liCyXk0zxijn0=

