matrix:
  include:
    - language: python
      python:
        - 3.7
      before_install:
        - echo "python before_install"
      install:
        - echo "python install"
      script:
        - echo "python test"

    - language: node_js
      node_js:
        - 13.5.0
      before_install:
        - echo "node_js before_install"
      install:
        - npm install
      script:
        - echo "node_js test"
